/amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    always_reset_initial_pose: false
    base_frame_id: base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    cv_buffer_size: 10
    cv_cloud_topic: /limo/cv_package/visual_ptcld/points
    cv_enabled: true
    cv_map_topic: /limo/map_package/online/maps/cv_obstacle
    cv_min_points: 5.0
    cv_occupied_threshold: 50
    cv_sad_gain: 20.0
    cv_sync_tolerance: 0.2
    cv_voxel_size: 0.075
    cv_weight_factor: 0.0
    do_beamskip: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    laser_weight_factor: 1.0
    map_topic: /limo/map_package/online/maps/laser_map
    max_beams: 60
    max_particles: 800
    min_particles: 300
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: differential
    save_pose_rate: 0.5
    scan_topic: /scan
    set_initial_pose: false
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    use_sim_time: true
    workload_logging_enabled: true
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
